### ISSUE TITLE
怎么获取ipa和apk的图片信息呢

### ISSUE THREAD

**Issue by gaochangjian** [chenquincy/app-info-parser#1]
怎么获取ipa和apk的图片信息呢

**Comment by tyzero** [comment]
ipa不知道，apk的话，解析resources.arsc 根据icon的resourceID找到对应路径就可以了。

**Comment by chenquincy** [comment]
@gaochangjian  apk文件的图标在解析出来的信息里有，ipa的图标被苹果处理过，没办法直接获取，等有时间我把这坑处理一下

**Comment by dongjw321** [comment]
@gaochangjian 能否提供接口，可以直接获取到图片的内容，因为一般都需要ICON来显示，期待大神的更新

**Comment by chenquincy** [comment]
@dongjw321   你应该@错人了，不过大神不敢当，昨晚研究了一下，获取图片内容确认是可行的，预计这周末（也可能会跳票-。-）会更新一个新的版本支持获取安装包图标

**Comment by dongjw321** [comment]
@chenquincy 期待新的版本，能获取到ICON的内容，这样就可以直接显示

**Comment by chenquincy** [comment]
@dongjw321  周末临时在公司加班跳票了-。-，请给我一点时间，我会尽快搞定的（严肃认真脸）

**Comment by chenquincy** [comment]
@dongjw321  欢迎使用0.1.0版本，已支持icon获取

**Comment by chenquincy** [comment]
@gaochangjian 0.1.0版本已支持
