### ISSUE TITLE
ie浏览器打开直接报错，请问有兼容性测试吗

### ISSUE THREAD

**Issue by hey9162** [chenquincy/app-info-parser#11]
![image](https://user-images.githubusercontent.com/22787406/55719442-ce71b800-5a30-11e9-8a1f-e540c1aea71a.png)
ll

**Comment by chenquincy** [comment]
@hey9162  没有考虑过ie的兼容性，目测应该是语法不兼容，可以clone一份在本地修改babel配置尝试兼容

**Comment by hey9162** [comment]
![image](https://user-images.githubusercontent.com/22787406/55769073-f3f2d600-5ab1-11e9-83e8-72b67b520360.png)
重新配置了balel编译后运行的报错。。。。

**Comment by chenquincy** [comment]
@hey9162  这个你得具体到源码里去找不兼容的地方，不止是babel配置，还有polyfill，特定语法的兼容。因为兼容IE的投入产出比太低，所以暂时不考虑做，如果你有需求的话需要自行去适配，大概思路可以参考一下这个 https://segmentfault.com/a/1190000005128101。

**Comment by louisfj** [comment]
@hey9162 请问你的IE兼容性解决了吗？
