### ISSUE TITLE
打包时 压缩代码报错 ，具体如下

### ISSUE THREAD

**Issue by Corgis** [chenquincy/app-info-parser#15]
webpack4 生产打包时 报如下错
from UglifyJs\nUnexpected token keyword «function», expected punc «,» [./node_modules/app-info-parser/src/apk.js:42,0]

**Comment by chenquincy** [comment]
@Corgis  打包时未将es7转化到es5, webpack的uglifyjs不支持es7所以报错, 0.2.5版本已修复, 感谢反馈
