### ISSUE TITLE
库以来的包报错isIphoneCompressed，是否需要自己的工程配置

### ISSUE THREAD

**Issue by Corgis** [chenquincy/app-info-parser#16]
UglifyJs\nUnexpected token: name (isIphoneCompressed) [./node_modules/cgbi-to-png/index.js:51,0]

**Comment by Corgis** [comment]
库以来的第三方包中 所有用了es6语法的都导致打包报错，应该不需要自己的工程去找出这些以来包一个个去配置编译吧？from UglifyJs\nUnexpected token: keyword (const) [./node_modules/crc/create_buffer.js

**Comment by chenquincy** [comment]
@Corgis 依赖包没有兼容到es2015，不过这个我无法控制，因此需要在webpack工程中配置babel打包，不需要单独去找，配置打包app-info-parser即可
![image](https://user-images.githubusercontent.com/10976378/57509149-18063900-7336-11e9-9bf6-3d50f40068f6.png)

**Comment by Corgis** [comment]
方便加个好友么，大神。738782092

**Comment by chenquincy** [comment]
@Corgis 问题没解决么？

**Comment by Corgis** [comment]
解决了 
exclude:[
						/node_modules\/(?!(cgbi-to-png|crc|app-info-parser)\/)/
					],
					include:[
						path.resolve(__dirname,'../src'),
						// path.resolve(__dirname,'../node_modules/cgbi-to-png'),
						// path.resolve(__dirname,'../node_modules/crc'),
						path.resolve(__dirname,'../node_modules/app-info-parser')
					],
但我 要把报错的都写进去 如果 这些 app-info-parser 还是报错
