### ISSUE TITLE
The new version doesn't work

### ISSUE THREAD

**Issue by relbraun** [chenquincy/app-info-parser#17]
I have installed the new version and tring to use it on a browser (Chrome) and I see this error in the console:

 
`Uncaught ReferenceError: regeneratorRuntime is not defined`

**Browser version (74.0.3729.131):**
 - Browser [chrome latest on windows]

**Comment by chenquincy** [comment]
@relbraun It seems like miss `transform-runtime` in your babel setting.
``` shell
npm install -D babel-plugin-transform-runtime
```
then add `plugins` to your babel config
``` json
{
    "plugins": ["transform-runtime"]
}
```

**Comment by chenquincy** [comment]
To resolve the compatibility issues, I will publish a compatible version at this weekend(may be few days later).

**Comment by relbraun** [comment]
What I have to do to make this feature run on internet explorer?

**Comment by chenquincy** [comment]
@relbraun  This library don't support to IE.

**Comment by chenquincy** [comment]
@relbraun v0.3.0 has been published. It resolves the `regeneratorRuntime is not defined`, you don't need to add `babel-plugin-transform-runtime` any more.
