### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by JesseWo** [chenquincy/app-info-parser#2]
AppInfoParser 的构造方法中这样写不合理吧。。
`
this.file = fs.readFileSync(path.join(__dirname, filename));
`
把 `/Users/xxxxx/demo/static/aaa.apk` 传进去，就成这了
`/Users/xxxxx/demo/node_modules/app-info-parser/src/Users/xxxxx/demo/static/aaa.apk`

**Comment by chenquincy** [comment]
@JesseWo  已知问题，0.0.8版本已修复，感谢反馈
