### ISSUE TITLE
import 引入报错

### ISSUE THREAD

**Issue by yyhuaisha** [chenquincy/app-info-parser#23]
错误信息如下：
ERROR in ./node_modules/bplist-parser/bplistParser.js
Module not found: Error: Can't resolve 'fs' in 'E:\dev\youdu_back_end\node_modules\bplist-parser'
ERROR in ./node_modules/app-info-parser/src/zip.js
Module not found: Error: Can't resolve 'path' in 'E:\dev\youdu_back_end\node_modules\app-info-parser\src'
ERROR in ./node_modules/streamifier/lib/index.js
Module not found: Error: Can't resolve 'stream' in 'E:\dev\youdu_back_end\node_modules\streamifier\lib'
ERROR in ./node_modules/cgbi-to-png/index.js
Module not found: Error: Can't resolve 'zlib' in 'E:\dev\youdu_back_end\node_modules\cgbi-to-png'

![image](https://user-images.githubusercontent.com/13938131/63510920-6cfb4300-c512-11e9-9e40-4c585017d301.png)

**Comment by chenquincy** [comment]
@yyhuaisha  Add the follow configuration to your `webpack.config.js`:
``` js
node: {
  fs: 'empty'
}
```

**Comment by dreamersss** [comment]
我用angular写的，也出现上面的问题，怎么办

**Comment by chenquincy** [comment]
@dreamersss  angular使用内置的 webpack-cli 处理，所以没办法直接修改。我刚刚看了一下可以解决，我明天帮你修复这个问题。

**Comment by chenquincy** [comment]
@dreamersss  问题已修复，你用最新的 0.3.4 版本试试

**Comment by dreamersss** [comment]
fs解决了，剩下的三个path,stream,zlib还是报错

**Comment by chenquincy** [comment]
@dreamersss  我这边似乎没什么问题，angular我不怎么用，建议你可以选择引入 `dist/app-info-parser.min.js`。
``` html
<script src="<your path>/app-info-parser.min.js">
```
使用的话直接使用 `new AppInfoParser` 即可
