### ISSUE TITLE
IPA 包 解析失败

### ISSUE THREAD

**Issue by zhs077** [chenquincy/app-info-parser#24]
用 你提供的地址，上传一个包，提示 解析出错：Error: inflating: invalid stored block lengths

**Comment by chenquincy** [comment]
@zhs077 可以的话麻烦提供一下测试的安装包

**Comment by zhs077** [comment]
有联系方式吗？怎么把包给你

**Comment by chenquincy** [comment]
@zhs077  你可以上传到网盘然后贴个链接，或者直接发到我的邮箱 mail@quincychen.cn
