### ISSUE TITLE
parseBplist is not a function 

### ISSUE THREAD

**Issue by Zo3i** [chenquincy/app-info-parser#25]
err ---->  TypeError: parseBplist is not a function     
at IpaParser._parsePlist (ipa.js?228c:108)     
at eval (ipa.js?228c:73)

打开源码发现这个函数有问题。。。

![image](https://user-images.githubusercontent.com/30296801/65745243-a6385b80-e12d-11e9-9f8f-3704cb25e5d6.png)

![image](https://user-images.githubusercontent.com/30296801/65745266-b6503b00-e12d-11e9-8cde-b12e8b8c599e.png)

**Comment by chenquincy** [comment]
@Zo3i  试试 v0.3.5 版本，如果可以的话，麻烦提供一下出此问题的安装包，方便我覆盖测试用例~。

**Comment by Zo3i** [comment]
刚刚看了一下，我使用的是vue。npm引入的。直接下载js文件引入是没问题的。

**Comment by chenquincy** [comment]
@Zo3i  你试试用最新版本 0.3.5，直接引入和npm引入是不同的打包方式。

**Comment by Zo3i** [comment]
暂时还没那么多测试用例。目前看来是没问题的。我的分发平台准备上线测试了。
