### ISSUE TITLE
0.2.5版本 新项目安装提示 fatal: repository 'https://github.com/chenquincy/isomorphic-unzip/' not found

### ISSUE THREAD

**Issue by Corgis** [chenquincy/app-info-parser#26]
Arguments: ls-remote --tags --heads https://github.com/chenquincy/isomorphic-unzip
Directory: F:\www\terminal-web-manager
Output:
remote: Repository not found.
fatal: repository 'https://github.com/chenquincy/isomorphic-unzip/' not found

**Comment by chenquincy** [comment]
@Corgis 请更新到最新版本 0.3.5

**Comment by Corgis** [comment]
0.3.5的版本 用法没变吧
