### ISSUE TITLE
IPA 圖片解析失敗

### ISSUE THREAD

**Issue by sp3580** [chenquincy/app-info-parser#27]
您好，用您提供的網址上傳IPA包，圖片會顯示不正常，能請幫忙查看一下嗎感謝
https://sp3580.github.io/iosfile/iosapp.ipa

**Comment by chenquincy** [comment]
@sp3580  ipa文件中的png文件被特殊处理过，需要经过转码，转码使用的是cgbi-to-png，应该和这个是同一个问题：https://github.com/jakubknejzlik/cgbi-to-png/issues/5，我已经向作者反馈问题。

**Comment by sp3580** [comment]
您好，這邊有自行調整一下，測試圖片不會破圖了，但 size 會變小....
能請幫忙查看一下嗎? 感謝您
https://sp3580.github.io/iosfile/iosapp2.ipa

**Comment by chenquincy** [comment]
@sp3580  size变小是指从什么尺寸变到什么尺寸？这个ipa我解析出来是120*120px

**Comment by sp3580** [comment]
解析出來應該要是 180x180 的，但卻是 120x120

**Comment by chenquincy** [comment]
@sp3580 解析出来的图标正则是 AppIcon-IB0020160x60 ，图标中存在 AppIcon-IB0020160x60@2x.png, AppIcon-IB0020160x60@3x.png, 拿的是 2x.png, 尺寸为120*120

**Comment by chenquincy** [comment]
@sp3580 你说的 180*180px 是 3x.png
