### ISSUE TITLE
basic用法，出现报错，没太看懂报错内容

### ISSUE THREAD

**Issue by Object-oriented** [chenquincy/app-info-parser#3]
我用basic用法，上传完文件之后便出现了报错提示。
这是报错内容：Uncaught (in promise) Error: End of data reached (data length = 14390685, asked index = 14409888). Corrupted zip ?

**Comment by chenquincy** [comment]
@Object-oriented  我写的解析工具依赖于jszip解压安装包，问题原因大概是jszip不支持读取某种压缩类型的文件，等有空我会尝试解决这个问题，谢谢反馈~

**Comment by chenquincy** [comment]
@Object-oriented  0.1.0版本已修复该问题，感谢反馈

**Comment by Object-oriented** [comment]
> @面向对象 0.1.0版本已修复该问题，感谢反馈

谢谢^_^
