### ISSUE TITLE
解析ipa包时发生错误，提示 TypeError: Cannot read property 'documentElement' of undefined

### ISSUE THREAD

**Issue by y5134828** [chenquincy/app-info-parser#30]
**描述 bug**
解析ipa包时发生错误，提示 TypeError: Cannot read property 'documentElement' of undefined
![image](https://user-images.githubusercontent.com/30194048/71239639-03fdcd80-2342-11ea-95fc-f694f516d243.png)

**复现**
请描述复现该bug的步骤:
1. 解析ipa包发生错误

**预期表现**
返回解析数据

**请填写您的Node或浏览器版本:**
 - Browser  chrome 78.0.3904.87（正式版本

**请提供测试用的安装包下载链接:**
-

**Comment by chenquincy** [comment]
@y5134828  能否提供测试用的安装包？

**Comment by y5134828** [comment]
@chenquincy  测试包已发送邮箱，谢谢。

**Comment by chenquincy** [comment]
@y5134828  问题已修复，你可以使用 0.3.6 版本
