### ISSUE TITLE
Parser resources.arsc error: RangeError: Illegal offset: 0 <= 50372 (+2) <= 50372

### ISSUE THREAD

**Issue by asdwsx1234** [chenquincy/app-info-parser#34]
**描述 bug**
解析facebook的apk时报错

**请填写您的Node或浏览器版本:**
 - Browser chrome 79.0.3945.88

**请提供测试用的安装包下载链接:**
- https://scontent-hkg3-2.xx.fbcdn.net/v/t39.10537-6/10000000_480734505901203_9023220891504345088_n.apk/Facebook_v_250_187584895.apk?_nc_cat=109&atg=sl.1tMZgRpEhNCEIm9JV&atgo=48238600&atgs=AUIMc2KvhbYmhdZUE9yb_yiG8G57WLfD133Vt4IDyRnB3Q&_nc_ohc=VaRE7X7pQxMAQlksrTDZspgzZmMsXhjk3bMyJJhCofLq8JuWz26OdSWBA&_nc_ht=scontent-hkg3-2.xx&oh=6b0e53888afe3031a2fad2caa399c595&oe=5EB0C82D

**Comment by chenquincy** [comment]
@asdwsx1234  问题已修复，你试试0.3.7版本，感谢反馈。

**Comment by asdwsx1234** [comment]
> @asdwsx1234 问题已修复，你试试0.3.7版本，感谢反馈。

谢谢！

**Comment by asdwsx1234** [comment]
> @asdwsx1234 问题已修复，你试试0.3.7版本，感谢反馈。

在0.3.10又重新出现了

**Comment by chenquincy** [comment]
> > @asdwsx1234 问题已修复，你试试0.3.7版本，感谢反馈。
> 
> 在0.3.10又重新出现了

@asdwsx1234  麻烦提供一下测试包链接，感觉应该 0.3.7 也会有问题，你可以退回 0.3.7 试试

**Comment by asdwsx1234** [comment]
0.3.7没问题， 已经退回0.3.7使用。
测试包链接：
https://cowtransfer.com/s/5ee7b1c0358340

**Comment by weekitmo** [comment]
0.3.7 也有问题 Error: Parser resources.arsc error: RangeError: Illegal offset: 0 <= 3712 (+1) <= 3712

**Comment by asdwsx1234** [comment]
> 0.3.7 也有问题 Error: Parser resources.arsc error: RangeError: Illegal offset: 0 <= 3712 (+1) <= 3712

提供一下测试包呗， 方便作者定位问题

**Comment by weekitmo** [comment]
@chenquincy 
![image](https://user-images.githubusercontent.com/21186859/93044357-292c2c00-f687-11ea-8f93-2216292380f4.png)

我修改 源码 ResourceFinder.prototype.processStringPool 这个方法 位运算 解决了

**Comment by chenquincy** [comment]
@weekitmo 麻烦提供一下测试包链接，我看看具体问题

**Comment by weekitmo** [comment]
> @weekitmo 麻烦提供一下测试包链接，我看看具体问题

链接: https://pan.baidu.com/s/1C5gvqYzCDnv68gnHQ_oUag  密码: kw12


@chenquincy
