### ISSUE TITLE
not a png file

### ISSUE THREAD

**Issue by freefer** [chenquincy/app-info-parser#36]
**描述 bug**
not a png file

**复现**
请描述复现该bug的步骤:
1. 选择XYQP_2020_1_8(1).ipa

**预期表现**
解析得到成功结果

**请填写您的Node或浏览器版本:**
版本 79.0.3945.117（正式版本） （64 位）

**请提供测试用的安装包下载链接:**
- https://cj.iphone-mingzhi.cn:444/Resources/XYQP_2020_1_8(1).ipa

**Comment by chenquincy** [comment]
@freefer  包链接无法下载

**Comment by chenquincy** [comment]
@freefer  0.3.8版本已修复该问题
