### ISSUE TITLE
部分IPA文件无法正常解析图标

### ISSUE THREAD

**Issue by anengag** [chenquincy/app-info-parser#42]
**描述 bug**
请简明扼要的描述你所遇到的bug
部分IPA文件无法正常解析图标

**复现**
请描述复现该bug的步骤:
1. 安装包图标也正常， 但是无法解析出应用包内图标
2. 测试在解析ipa文件时出现

**预期表现**
请简明扼要的描述你所期望得到的效果

**请填写您的Node或浏览器版本:**
Google Chrome 已是最新版本
版本 80.0.3987.132（正式版本） （64 位）

**请提供测试用的安装包下载链接:**
测试安装包地址 https://gf-lyres.oss-cn-beijing.aliyuncs.com/test_tubiao.ipa

**Comment by chenquincy** [comment]
@anengag 用你的包解析了一下，查看了解析过程，这个包的打包是有问题的。
`info.plist` 中解析出来的图标路径为：
```
info.CFBundleIcons.CFBundlePrimaryIcon.CFBundleIconFiles ====>  [
  'AppIcon20x20',
  'AppIcon29x29',
  'AppIcon40x40',
  'AppIcon57x57',
  'AppIcon60x60'
]
```
查看包内容发现，图标命名格式为：
```
Icon-50.png
Icon-72.png
...
Icon-xx.png
```
两者对应不上，因此无法正常解析图标

**Comment by sunnylqm** [comment]
我也发现有图标解析失败的情况，还没有具体分析原因，但ipa是从xcode标准流程导出的
建议这里可以忽略错误输出警告，而不要直接抛出异常导致整个parse失败 @chenquincy
