### ISSUE TITLE
请发布dist目录到npm并更新browser配置

### ISSUE THREAD

**Issue by mudio** [chenquincy/app-info-parser#43]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Node or Browser version (please complete the following information):**
 - Browser [e.g. chrome72.0.3626.121]
 - Node [e.g. v8.9.4]

**Package links for testing(downloadable links of the package, which making this issue)**
- http://xxx.com/test-apk.apk

**描述 bug**
请简明扼要的描述你所遇到的bug

**复现**
请描述复现该bug的步骤:
1. ...
2. ...

**预期表现**
请简明扼要的描述你所期望得到的效果

**请填写您的Node或浏览器版本:**
 - Browser [如：chrome72.0.3626.121]
 - Node [如：v8.9.4]

**请提供测试用的安装包下载链接:**
- http://xxx.com/test-apk.apk

**Comment by chenquincy** [comment]
@mudio dist目录不需要被发布到NPM，能说明一下你的这个issue所要解决的问题么？

**Comment by mudio** [comment]
两个场景，一个是浏览器端依赖基于npm镜像的cdn服务，例如unpkg，另一个webpack构建web应用优先读取browser，读取main是非预期行为



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: QuincyChen <notifications@github.com&gt;
发送时间: 2020年3月24日 00:30
收件人: chenquincy/app-info-parser <app-info-parser@noreply.github.com&gt;
抄送: 木休大人 <523317421@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[chenquincy/app-info-parser] 请发布dist目录到npm并更新browser配置 (#43)





 
@mudio dist目录不需要被发布到NPM，能说明一下你的这个issue所要解决的问题么？

**Comment by chenquincy** [comment]
@mudio dist目录已发布到NPM，0.3.10 版本。browser配置会导致webpack打包出现问题，暂时还没有时间去解决，欢迎提供mr。
