### ISSUE TITLE
直接使用文件路径解析报错

### ISSUE THREAD

**Issue by Moking1997** [chenquincy/app-info-parser#46]
`  const AppInfoParser = require("app-info-parser");
      const parser = new AppInfoParser("./packages/dbb.apk"); // or xxx.ipa
      parser
        .parse()
        .then(result => {
          console.log("app info ----> ", result);
          console.log("icon base64 ----> ", result.icon);
        })
        .catch(err => {
          console.log("err ----> ", err);
        });`

报错信息：
`main.vue?5faf:137 Uncaught Error: Param error: [file] must be an instance of Blob or File in browser.`

我用其他apk解析插件同样的路径是可以解析的，是我的写法有问题么

**Comment by chenquincy** [comment]
@Moking1997  你在使用vue对吧，浏览器端没有文件路径这一说法啊

**Comment by Moking1997** [comment]
我在使用`vue-electron`来做桌面应用，我刚刚测试了一下，直接创建一个js文件是可以正常解析的，但是我如果将代码放进`vue- electron`中就会报刚刚的错误

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: QuincyChen<mailto:notifications@github.com>
发送时间: 2020年4月21日 11:32
收件人: chenquincy/app-info-parser<mailto:app-info-parser@noreply.github.com>
抄送: Moking1997<mailto:Moking1997@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [chenquincy/app-info-parser] 直接使用文件路径解析报错 (#46)


@Moking1997<https://github.com/Moking1997> 你在使用vue对吧，浏览器端没有文件路径这一说法啊

―

**Comment by chenquincy** [comment]
@Moking1997  electron 我没有试过，桌面应用解析安装包，正常来说也应该有一个选择文件的过程吧，你这个用法是用在 Node 端的

**Comment by Moking1997** [comment]
好的，谢谢你的回复，我再找找其他办法

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: QuincyChen <notifications@github.com>
发送时间: Tuesday, April 21, 2020 11:42:43 AM
收件人: chenquincy/app-info-parser <app-info-parser@noreply.github.com>
抄送: Moking1997 <Moking1997@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [chenquincy/app-info-parser] 直接使用文件路径解析报错 (#46)


@Moking1997<https://github.com/Moking1997> electron 我没有试过，桌面应用解析安装包，正常来说也应该有一个选择文件的过程吧，你这个用法是用在 Node 端的

―

**Comment by grace618** [comment]
我也是electron 这个问题

**Comment by chenquincy** [comment]
@grace618 可以用 `1.0.1-alpha.1` 版本试试

**Comment by grace618** [comment]
> @grace618 可以用 `1.0.1-alpha.1` 版本试试

不行，路径使用文件的绝对路径，例如C://xx/xx ，我翻来覆去的测试，怎么都不行

**Comment by chenquincy** [comment]
没写过 electron ，看起来是文件系统的规则和 h5 不一样，得等我有空再看看了



    


            在2021年04月22日 11:53，grace618 写道： 



@grace618 可以用 1.0.1-alpha.1 版本试试



不行，路径使用文件的绝对路径，例如C://xx/xx ，我翻来覆去的测试，怎么都不行



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/chenquincy/app-info-parser/issues/46#issuecomment-824518121",

"url": "https://github.com/chenquincy/app-info-parser/issues/46#issuecomment-824518121",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by grace618** [comment]
> 没写过 electron ，看起来是文件系统的规则和 h5 不一样，得等我有空再看看了 在2021年04月22日 11:53，grace618 写道： @grace618 可以用 1.0.1-alpha.1 版本试试 不行，路径使用文件的绝对路径，例如C://xx/xx ，我翻来覆去的测试，怎么都不行 —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#46 (comment)](https://github.com/chenquincy/app-info-parser/issues/46#issuecomment-824518121)", "url": "[#46 (comment)](https://github.com/chenquincy/app-info-parser/issues/46#issuecomment-824518121)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

现在解决了，代码没问题，这个提问者是因为没分清在浏览器端和node端使用，用electron应该在主进程里面使用
