### ISSUE TITLE
1. 通过npm引入

### ISSUE THREAD

**Issue by Tzrong** [chenquincy/app-info-parser#47]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Node or Browser version (please complete the following information):**
 - Browser [e.g. chrome72.0.3626.121]
 - Node [e.g. v8.9.4]

**Package links for testing(downloadable links of the package, which making this issue)**
- http://xxx.com/test-apk.apk

**描述 bug**
请简明扼要的描述你所遇到的bug

**复现**
请描述复现该bug的步骤:
1. ...
2. ...

**预期表现**
请简明扼要的描述你所期望得到的效果

**请填写您的Node或浏览器版本:**
 - Browser [如：chrome72.0.3626.121]
 - Node [如：v8.9.4]

**请提供测试用的安装包下载链接:**
- http://xxx.com/test-apk.apk

**Comment by chenquincy** [comment]
@Tzrong  请写好 issue 描述，没看出来你的问题是什么

**Comment by chenquincy** [comment]
bug 描述不清
