### ISSUE TITLE
vue项目中通过npm引入报错

### ISSUE THREAD

**Issue by Tzrong** [chenquincy/app-info-parser#48]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Node or Browser version (please complete the following information):**
 - Browser [e.g. chrome72.0.3626.121]
 - Node [e.g. v8.9.4]

**Package links for testing(downloadable links of the package, which making this issue)**
- http://xxx.com/test-apk.apk

**描述 bug**
请简明扼要的描述你所遇到的bug

**复现**
请描述复现该bug的步骤:
1. 通过npm引入
2. 
```
import AppInfoParser from 'app-info-parser'
 const parser = new AppInfoParser('https://res.12317wan.com/mailiang/cyad/cyqlb_981.apk')
        parser
            .parse()
            .then(result => {
                console.log('app info ----> ', result)
            })
            .catch(err => {
                console.log('err ----> ', err)
            })Ï
````

报错
```
vue.esm.js:628 [Vue warn]: Error in created hook: "Error: Param error: [file] must be an instance of Blob or File in browser."
```
通过[链接](https://app-info-parser.quincychen.cn/)是可以正常解析的
**预期表现**
预期可以解析apk包

**请填写您的Node或浏览器版本:**
 - Browser [如：chrome81.0.4044.138（正式版本]
 - Node [如：v10.15.3]

**请提供测试用的安装包下载链接:**
- https://res.12317wan.com/mailiang/cyad/cyqlb_981.apk

**Comment by chenquincy** [comment]
@Tzrong  不支持通过链接的方式解析，请自行下载 apk 文件，浏览器端只能解析文件类型或者 blob 类型。
