### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by lvchunai** [chenquincy/app-info-parser#55]
**Describe the bug**
react项目 客户端引入报错
**ERROR in ./node_modules/bplist-parser/bplistParser.js
Module not found: Error: Can't resolve 'fs'**

**解决办法**
package.json中入口文件找不到
![image](https://user-images.githubusercontent.com/23652521/105978992-224e0500-60ce-11eb-9352-f931c35aae1d.png)

修改之后解决问题，还请修复以下这个问题哦 
"browser": "./dist/app-info-parser.js",

**Comment by chenquincy** [comment]
@lvchunai 可以给个 demo 么？我这无法复现
