### ISSUE TITLE
utils里面findApkIconPath函数取图片icon是什么规则

### ISSUE THREAD

**Issue by grace618** [chenquincy/app-info-parser#57]
我看了代码也没明白，是写错了吗,为什么没有dpi大于120的，就取数组里第一个

**Comment by chenquincy** [comment]
> 我看了代码也没明白，是写错了吗,为什么没有dpi大于120的，就取数组里第一个

@grace618 当有大于 120 的图标，说明对 icon 清晰度有要求，所以取最大的一个。如果没有 120 以上的，就拿最小的那个图标

**Comment by grace618** [comment]
> > 我看了代码也没明白，是写错了吗,为什么没有dpi大于120的，就取数组里第一个
> 
> @grace618 当有大于 120 的图标，说明对 icon 清晰度有要求，所以取最大的一个。如果没有 120 以上的，就拿最小的那个图标

如果我想选择特定尺寸的icon，请问应该怎么做呢

**Comment by grace618** [comment]
> > > 我看了代码也没明白，是写错了吗,为什么没有dpi大于120的，就取数组里第一个
> > 
> > 
> > @grace618 当有大于 120 的图标，说明对 icon 清晰度有要求，所以取最大的一个。如果没有 120 以上的，就拿最小的那个图标
> 
> 如果我想选择特定尺寸的icon，请问应该怎么做呢
