### ISSUE TITLE
获取解析后信息里面的文件名为数组

### ISSUE THREAD

**Issue by grace618** [chenquincy/app-info-parser#60]
获取解析后信息里面的文件名为数组，现在查出来是['apple','苹果','xxx']无法知道哪个语言是如何对应的，能否区分对应一下语言，得到{‘zh_CN’:'苹果','en_US':'apple'}

**Comment by chenquincy** [comment]
@grace618  这个功能预计在 2.0 版本实现，但具体实现时间还不确定。如果着急的话可以发个 alpha 版本给你使用。

**Comment by grace618** [comment]
> @grace618 这个功能预计在 2.0 版本实现，但具体实现时间还不确定。如果着急的话可以发个 alpha 版本给你使用。

行的话，麻烦你了

**Comment by chenquincy** [comment]
@grace618  1.1.1-alpha.1 已发布，需要固定版本号使用。如满足需求请关闭 issue。

**Comment by chenquincy** [comment]
@grace618 长时间未回复，我先关闭 issue 了。有需要可以重开 issue。
