### ISSUE TITLE
versionName 出现乱码，但aapt解压是正常

### ISSUE THREAD

**Issue by weekitmo** [chenquincy/app-info-parser#61]
**Describe the bug**
解析部分 apk 的versionName 乱码 （VersionName of the parsing part of the APK is messy code）

![image](https://user-images.githubusercontent.com/21186859/118636887-c1c30f00-b807-11eb-9fc9-4888c89c2c3b.png)

但是我用 aapt dump badging 命令解析是正常的 （But I use the `aapt dump badging` command, it works fine）

![image](https://user-images.githubusercontent.com/21186859/118636978-e15a3780-b807-11eb-83f0-d1e891152510.png)

我尝试 debug 源码，可能是binary.js的问题？(I had try to debug the source, maybe a problem with binary.js?)

**Expected behavior**
Work expected.

**请填写您的Node或浏览器版本:**
 - chrome
 - Node 14.5

**请提供测试用的安装包下载链接:**
- 链接: https://pan.baidu.com/s/1kgHgQtb43xAdDQnMTDbt_g 提取码: daji

**Comment by chenquincy** [comment]
@weekitmo 不好意思回复晚了，最近在封闭开发，暂时没有时间去修复这个 bug，如果可以的话欢迎提供 pr 或者等我后续有空修复。

**Comment by chenquincy** [comment]
@weekitmo 抱歉拖的时间比较长，问题已修复，可以试试 1.1.2 版本
