### ISSUE TITLE
[file] must be an instance of Blob or File in browser.

### ISSUE THREAD

**Issue by liujiayi13** [chenquincy/app-info-parser#68]
请问这个const parser = new AppInfoParser('../packages/xxx.apk') ;传的值应该是什么格式的

**Comment by 17628673421** [comment]
I still don't understand the usage in the example, could you explain it in more detail? I saw that mistake too!

**Comment by chenquincy** [comment]
> I still don't understand the usage in the example, could you explain it in more detail? I saw that mistake too!

Sry for the late reply, you can just read the example in [basic-use.html](https://github.com/chenquincy/app-info-parser/blob/master/example/basic-use.html). You should get the file blob by an input element while using in browser.
