### ISSUE TITLE
APP应用名称和大小这么重要的信息能否获取到？

### ISSUE THREAD

**Issue by DreamPWJ** [chenquincy/app-info-parser#71]
还有构建号等等

**Comment by chenquincy** [comment]
这些在解析结果里都有，至于对应哪个字段，根据安卓还是 iOS 查询一下

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/148516759-49ada243-944b-42cd-aa18-1bd1a6a969e4.png)
应用名称有，但是包大小没有啊@chenquincy

**Comment by chenquincy** [comment]
@DreamPWJ 包大小直接读 file.size 就可以了吧   不需要经过解析啊

**Comment by DreamPWJ** [comment]
> @DreamPWJ 包大小直接读 file.size 就可以了吧 不需要经过解析啊

能提供不是更好？ 自动转换成KB MB

**Comment by DreamPWJ** [comment]
android 新格式aab的能解析吗
