### ISSUE TITLE
ipa.js那个文件缺少了在浏览器端cgbi到png的转换过程导致浏览器端转出来的icon不对

### ISSUE THREAD

**Issue by arrosev** [chenquincy/app-info-parser#79]
ipa.js 42行plistInfo.icon = iconBuffer ? getBase64FromBuffer(window.btoa(String.fromCharCode(...iconBuffer))) : null这边没有转换啊

**Comment by arrosev** [comment]
浏览器端貌似用不了cgbiToPng.revert这个函数

**Comment by chenquincy** [comment]
请提供一下测试用的包

**Comment by arrosev** [comment]
> 请提供一下测试用的包
我的开发环境是vite2+vue3

**Comment by arrosev** [comment]
> 请提供一下测试用的包

测试包：https://qdhw9.leaderhero.com/repof/20220610/Delta_v1.3.1_os12.2__220610173113_pandahelp.vip.ipa

**Comment by chenquincy** [comment]
@arrosev  可以在这里试试 https://app-info-parser.quincychen.cn/，我试了一下可以解析出来图片。

**Comment by arrosev** [comment]
> @arrosev 可以在这里试试 [app-info-parser 测试](https://app-info-parser.quincychen.cn/) ，我试了一下可以解析出来图片。

那说明在浏览端它也走了cgbiToPng.revert这个函数，那就没问题了，我的问题应该是和vue的环境有关，这个问题可以关闭了
