### ISSUE TITLE
This tool can obtain apk signature for verification when uploading？such as Md5，SHA1，SHA256

### ISSUE THREAD

**Issue by Java-Coffee-Mechine** [chenquincy/app-info-parser#82]
签名:

所有者: CN=刘金瑞, OU=奇艺, O=奇艺, L=Beijing, ST=Beijing, C=CN
发布者: CN=刘金瑞, OU=奇艺, O=奇艺, L=Beijing, ST=Beijing, C=CN
序列号: 4c9da6a0
生效时间: Sat Sep 25 15:37:04 CST 2010, 失效时间: Sun Jun 28 15:37:04 CST 2065
证书指纹:
         SHA1: 23:27:02:6C:42:B5:91:E1:8E:12:BD:E1:FD:FD:73:53:F7:BE:05:33
         SHA256: BF:46:EA:E9:85:C1:AB:0D:63:68:33:67:0C:36:86:BC:44:3E:49:F3:7D:75:DE:C5:90:9A:DC:B5:87:A8:0A:B4
签名算法名称: SHA1withRSA (弱)
主体公共密钥算法: 1024 位 RSA 密钥 (弱)
版本: 3

**Comment by chenquincy** [comment]
This package can't support it. You can find someone else for that.
