### ISSUE TITLE
apk 中 icon 命名不规范，导致获取的 icon 不是不是最清晰的

### ISSUE THREAD

**Issue by snowtreetree** [chenquincy/app-info-parser#88]
apk 包 icon 命名不规范，导致获取的 icon 不是不是最清晰的，不太确定是不是可以将 `findApkIconPath`  函数替换掉，如下：  

- 个人觉得这么实现可能不太优雅，（`findApkIconPath`也没用了），😂。
- 另外我截图里面 icon 的顺序，其实是和这些 icon 的大小是一致的（不知道是不是有关联）。

```
Promise.all(apkInfo.application.icon.map(iconPath => this.getEntry(iconPath))).then(icons => {
  const iconBuffer = icons.sort((a, b) => b.length - a.length)[0]
  apkInfo.icon = iconBuffer ? getBase64FromBuffer(iconBuffer) : null
  resolve(apkInfo)
}).catch(e => {
  apkInfo.icon = null
  resolve(apkInfo)
  console.warn('[Warning] failed to parse icon: ', e)
})
```

![image](https://user-images.githubusercontent.com/30932683/236473406-60b3b7af-3dce-40a5-a46c-f947aff87138.png)

**Comment by chenquincy** [comment]
@snowtreetree 之前遇到过 icon 中包含其他图片的情况。这么改没法确保获取的图标是对的。

**Comment by snowtreetree** [comment]
好吧。
包含了其他图片的话，`findApkIconPath`  也可能会出错（命名不规范 && `apkInfo.application.icon[0]` 不是 icon）  ，不是在抬杠，只是想了解下场景，🥲。
看到其他 issue 里面提到知乎的包，icon 里面还有 .xml 类型的。

**Comment by chenquincy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    确实有时候会有问题，但是暂时没太多时间去完善这个东西。我看 issue 中有个老哥有想法来做这个事情，到时候看看做的咋样。
    
        
            
        
    
    
    
    

    

    

    在2023年05月8日 ***@***.***> 写道： 



好吧。
包含了其他图片的话，findApkIconPath  也可能会出错（命名不规范 && apkInfo.application.icon[0] 不是 icon）  ，不是在抬杠，只是想了解下场景，🥲。
看到其他 issue 里面提到知乎的包，icon 里面还有 .xml 类型的。

**Comment by chenquincy** [comment]
#91

**Comment by chenquincy** [comment]
Duplicate of #91
