### ISSUE TITLE
我发现ipa的包如果在没有添加Appicon的时候，会报错

### ISSUE THREAD

**Issue by shawn-tangsc** [chenquincy/app-info-parser#9]
报错
```
cannot read property 'slice' of undefined
```
应该是没有做数组的非空处理吧？

不过这个插件非常棒！谢谢作者！

**Comment by chenquincy** [comment]
@shawn-tangsc  能否提供一个可测试的ipa文件呢？我补充一下测试用例，顺便修复这个问题~

**Comment by mkerj** [comment]
err ---->  {/payload\/.+?.app\/info.plist$/i: Uint8Array(1246)}

**Comment by imquincychen** [comment]
@mkerj 麻烦提供一下测试文件

**Comment by mkerj** [comment]
随便读取 ipa 或 apk 都会报这个错误，app信息是读取出来的。

**Comment by chenquincy** [comment]
@mkerj 你给的信息太少了，我在本地安装了最新版本解析apk，ipa都没问题，你可以新建一个issue，按照issue模板补充一下信息

**Comment by chenquincy** [comment]
@shawn-tangsc  太长时间没有响应，issue先关闭了，后续有问题再开issue
