### ISSUE TITLE
目前区分运行环境的方式有点问题

### ISSUE THREAD

**Issue by chihai-chuck** [chenquincy/app-info-parser#94]
通过判断`window`和`document`对象是否存在来确定当前是browser还是nodejs环境，在有些场景中不合理，因为像`electron`是browser+nodejs的，这样还是会被判断成是browser。
我觉得可以改为通过判断`process`对象，如果`process`对象存在则是nodejs，否则就是browser。
因为browser环境不存在`process`，但是像`electron`的browser+nodejs还是会存在`window`和`docuemnt`的。
```javascript
typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]' // nodejs
typeof process === 'undefined' || Object.prototype.toString.call(process) !== '[object process]' // browser
```

**Comment by chenquincy** [comment]
仅仅通过 process 判断还是不太稳妥，如果用户声明了一个 window.process 的对象变量，这个判断就会有问题了。

**Comment by chenquincy** [comment]
并且判断 node 环境一般通过 global 做判断，用 process 的比较少，可以在原有的基础上再加上 global 是否存在的判断

**Comment by chihai-chuck** [comment]
> 仅仅通过 process 判断还是不太稳妥，如果用户声明了一个 window.process 的对象变量，这个判断就会有问题了。

所以还额外判断了process的原型类型，如果是用户创建的window.process对象，它的原型会是`[object Object]`，除非刻意的修改了原型类型
